version: 2.1

jobs:
  build:
    docker:
      - image: tensorflow/tensorflow:2.5.1
    steps:
      - checkout
      - run:
          name: install system dependencies
          command: |
            apt update && apt install -y git python3-venv wget
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
      - run:
          name: checkout submodules
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - restore_cache:
          keys:
            - 'app-dependencies-{{ checksum "./keras-flask-deploy-webapp/requirements.txt" }}'
            - app-dependencies-
      - run:
          name: install python dependencies
          command: |
            cd ./keras-flask-deploy-webapp
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: 'app-dependencies-{{ checksum "./keras-flask-deploy-webapp/requirements.txt" }}'
      - run:
          name: run lint
          command: |
            cd ./keras-flask-deploy-webapp
            . venv/bin/activate
            pylint --disable=R,C,W1203,W1202,E0611 app.py
            hadolint Dockerfile
