version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  lint:
    docker:
      - image: tensorflow/tensorflow:2.5.1
    steps:
      - checkout
      - run:
          name: install system dependencies
          command: |
            apt update && apt install -y git python3-venv wget
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
      - run:
          name: checkout submodules
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - restore_cache:
          keys:
            - 'app-dependencies-{{ checksum "./keras-flask-deploy-webapp/requirements.txt" }}'
            - app-dependencies-
      - run:
          name: install python dependencies
          command: |
            cd ./keras-flask-deploy-webapp
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: 'app-dependencies-{{ checksum "./keras-flask-deploy-webapp/requirements.txt" }}'
      - run:
          name: run lint
          command: |
            cd ./keras-flask-deploy-webapp
            . venv/bin/activate
            pylint --disable=R,C,W1203,W1202,E0611 app.py
            hadolint Dockerfile

  build-and-push-image:
    docker:
      - image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          region: us-east-1
          registry-id: AWS_ECR_REGISTRY_ID
          repo: nd991_capstone
          path: ./keras-flask-deploy-webapp
          tag: "latest,${CIRCLE_SHA1}"

workflows:
  default:
    jobs:
      - lint
      - build-and-push-image:
          requires: [lint]
