version: 2.1

jobs:
  build:
    docker:
      - image: tensorflow/tensorflow:2.5.1
    working_directory: ./keras-flask-deploy-webapp
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'app-dependencies-{{ checksum "requirements.txt" }}'
            - app-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: 'app-dependencies-{{ checksum "requirements.txt" }}'
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            pylint --disable=R,C,W1203,W1202,E0611 app.py
            hadolint Dockerfile
